const fixedWrongAnswers = {
    // Prepositions, conjunctions, and adverbs set
    "during, in between": ["behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "during": ["behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "behind": ["during, in between", "during", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "in front of": ["during, in between", "during", "behind", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "by, at the time of, in the eyes of, according to": ["during, in between", "during", "behind", "in front of", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "after": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "above": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "between, amongst": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "before, ago": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "under": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "with": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "around": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "for, belongs to": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "in": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "until, even": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "on": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "regarding, from": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "to, towards, until": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "like": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "from": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "there, at that time": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "there": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "here", "here", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "here": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "either or": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "not", "neither nor", "rather, but", "rather, but", "and", "then", "then"],
    "not": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "neither nor", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "neither nor": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "rather, but", "rather, but", "and", "then", "then", "either or", "either or"],
    "rather, but": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "and", "then", "then", "either or", "either or"],
    "and": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "then", "then", "either or", "either or"],
    "then": ["during, in between", "during", "behind", "in front of", "by, at the time of, in the eyes of, according to", "after", "above", "between, amongst", "before, ago", "under", "with", "around", "for, belongs to", "in", "until, even", "on", "regarding, from", "to, towards, until", "like", "from", "with", "there, at that time", "there", "here", "here", "there", "either or", "not", "neither nor", "rather, but", "rather, but", "and", "either or", "either or"],

    // Basic prepositions
    "however": ["from wherever, however", "however many", "whichever", "whoever", "whatever", "wherever", "whenever", "if"],
    "from wherever, however": ["however many", "whichever", "whoever", "whatever", "wherever", "whenever", "if"],
    "however many": ["however", "from wherever, however", "whichever", "whoever", "whatever", "wherever", "whenever", "if"],
    "whichever": ["however", "from wherever, however", "however many", "whoever", "whatever", "wherever", "whenever", "if"],
    "whoever": ["however", "from wherever, however", "however many", "whichever", "whatever", "wherever", "whenever", "if"],
    "whatever": ["however", "from wherever, however", "however many", "whichever", "whoever", "wherever", "whenever", "if"],
    "wherever": ["however", "from wherever, however", "however many", "whichever", "whoever", "whatever", "whenever", "if"],
    "whenever": ["however", "from wherever, however", "however many", "whichever", "whoever", "whatever", "wherever", "if"],
    "if": ["however", "from wherever, however", "however many", "whichever", "whoever", "whatever", "wherever", "whenever"],

    // Interrogative Words and Particle
    "when": ["how", "from where, how", "how many", "which", "why", "who does it belong to", "(interrogative particle)", "who", "what", "where"],
    "how": ["when", "from where, how", "how many", "which", "why", "who does it belong to", "(interrogative particle)", "who", "what", "where"],
    "from where, how": ["when", "how", "how many", "which", "why", "who does it belong to", "(interrogative particle)", "who", "what", "where"],
    "how many": ["when", "how", "from where, how", "which", "why", "who does it belong to", "(interrogative particle)", "who", "what", "where"],
    "which": ["when", "how", "from where, how", "how many", "why", "who does it belong to", "(interrogative particle)", "who", "what", "where"],
    "why": ["when", "how", "from where, how", "how many", "which", "who does it belong to", "(interrogative particle)", "who", "what", "where"],
    "who does it belong to": ["when", "how", "from where, how", "how many", "which", "why", "(interrogative particle)", "who", "what", "where"],
    "(interrogative particle)": ["when", "how", "from where, how", "how many", "which", "why", "who does it belong to", "who", "what", "where"],
    "who": ["when", "how", "from where, how", "how many", "which", "why", "who does it belong to", "(interrogative particle)", "what", "where"],
    "what": ["when", "how", "from where, how", "how many", "which", "why", "who does it belong to", "(interrogative particle)", "who", "where"],
    "where": ["when", "how", "from where, how", "how many", "which", "why", "who does it belong to", "(interrogative particle)", "who", "what"],

    // Quantifiers/Remainder - added many to make for four
    "some, one": ["remaining, rest of, all", "remainder, rest", "many"],
    "remaining, rest of, all": ["some, one", "remainder, rest", "many"],
    "remainder, rest": ["some, one", "remaining, rest of, all", "many"],

    // Verb Forms
    "(form of a verb)": ["to make مَرْفُوع", "to make مَنْصُوب", "to make مَجْزُوم"],
    "to make مَرْفُوع": ["(form of a verb)", "to make مَنْصُوب", "to make مَجْزُوم"],
    "to make مَنْصُوب": ["(form of a verb)", "to make مَرْفُوع", "to make مَجْزُوم"],
    "to make مَجْزُوم": ["(form of a verb)", "to make مَرْفُوع", "to make مَنْصُوب"],

    // Connectors
    "مَوْصُول (time)": ["أَنْ before quotation", "مَوْصُول (indicative)", "مَوْصُول (subjunctive)"],
    "أَنْ before quotation": ["مَوْصُول (time)", "مَوْصُول (indicative)", "مَوْصُول (subjunctive)"],
    "مَوْصُول (indicative)": ["مَوْصُول (time)", "أَنْ before quotation", "مَوْصُول (subjunctive)"],
    "مَوْصُول (subjunctive)": ["مَوْصُول (time)", "أَنْ before quotation", "مَوْصُول (indicative)"],

    // Days of the week
    "Monday": ["Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "Tuesday": ["Monday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "Wednesday": ["Monday", "Tuesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "Thursday": ["Monday", "Tuesday", "Wednesday", "Friday", "Saturday", "Sunday"],
    "Friday": ["Monday", "Tuesday", "Wednesday", "Thursday", "Saturday", "Sunday"],
    "Saturday": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Sunday"],
    "Sunday": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],

    // Islamic Months
    "Rajab": ["Shaban", "Ramadhan", "Shawwal", "Zul Qadah", "Zul Hijjah", "Muharram", "Safar", "Rabi al-Awal", "Rabi at-Thani", "Jumada al-Awal", "Jumada at-Thani"],
    "Shaban": ["Rajab", "Ramadhan", "Shawwal", "Zul Qadah", "Zul Hijjah", "Muharram", "Safar", "Rabi al-Awal", "Rabi at-Thani", "Jumada al-Awal", "Jumada at-Thani"],
    "Ramadhan": ["Rajab", "Shaban", "Shawwal", "Zul Qadah", "Zul Hijjah", "Muharram", "Safar", "Rabi al-Awal", "Rabi at-Thani", "Jumada al-Awal", "Jumada at-Thani"],
    "Shawwal": ["Rajab", "Shaban", "Ramadhan", "Zul Qadah", "Zul Hijjah", "Muharram", "Safar", "Rabi al-Awal", "Rabi at-Thani", "Jumada al-Awal", "Jumada at-Thani"],
    "Zul Qadah": ["Rajab", "Shaban", "Ramadhan", "Shawwal", "Zul Hijjah", "Muharram", "Safar", "Rabi al-Awal", "Rabi at-Thani", "Jumada al-Awal", "Jumada at-Thani"],
    "Zul Hijjah": ["Rajab", "Shaban", "Ramadhan", "Shawwal", "Zul Qadah", "Muharram", "Safar", "Rabi al-Awal", "Rabi at-Thani", "Jumada al-Awal", "Jumada at-Thani"],
    "Muharram": ["Rajab", "Shaban", "Ramadhan", "Shawwal", "Zul Qadah", "Zul Hijjah", "Safar", "Rabi al-Awal", "Rabi at-Thani", "Jumada al-Awal", "Jumada at-Thani"],
    "Safar": ["Rajab", "Shaban", "Ramadhan", "Shawwal", "Zul Qadah", "Zul Hijjah", "Muharram", "Rabi al-Awal", "Rabi at-Thani", "Jumada al-Awal", "Jumada at-Thani"],
    "Rabi al-Awal": ["Rajab", "Shaban", "Ramadhan", "Shawwal", "Zul Qadah", "Zul Hijjah", "Muharram", "Safar", "Rabi at-Thani", "Jumada al-Awal", "Jumada at-Thani"],
    "Rabi at-Thani": ["Rajab", "Shaban", "Ramadhan", "Shawwal", "Zul Qadah", "Zul Hijjah", "Muharram", "Safar", "Rabi al-Awal", "Jumada al-Awal", "Jumada at-Thani"],
    "Jumada al-Awal": ["Rajab", "Shaban", "Ramadhan", "Shawwal", "Zul Qadah", "Zul Hijjah", "Muharram", "Safar", "Rabi al-Awal", "Rabi at-Thani", "Jumada at-Thani"],
    "Jumada at-Thani": ["Rajab", "Shaban", "Ramadhan", "Shawwal", "Zul Qadah", "Zul Hijjah", "Muharram", "Safar", "Rabi al-Awal", "Rabi at-Thani", "Jumada al-Awal"],
  
    // Numbers 1-10
    "one": ["two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"],
    "two": ["one", "three", "four", "five", "six", "seven", "eight", "nine", "ten"],
    "three": ["one", "two", "four", "five", "six", "seven", "eight", "nine", "ten"],
    "four": ["one", "two", "three", "five", "six", "seven", "eight", "nine", "ten"],
    "five": ["one", "two", "three", "four", "six", "seven", "eight", "nine", "ten"],
    "six": ["one", "two", "three", "four", "five", "seven", "eight", "nine", "ten"],
    "seven": ["one", "two", "three", "four", "five", "six", "eight", "nine", "ten"],
    "eight": ["one", "two", "three", "four", "five", "six", "seven", "nine", "ten"],
    "nine": ["one", "two", "three", "four", "five", "six", "seven", "eight", "ten"],
    "ten": ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"],

    // Numbers 11-19
    "eleven": ["twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"],
    "twelve": ["eleven", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"],
    "thirteen": ["eleven", "twelve", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"],
    "fourteen": ["eleven", "twelve", "thirteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"],
    "fifteen": ["eleven", "twelve", "thirteen", "fourteen", "sixteen", "seventeen", "eighteen", "nineteen"],
    "sixteen": ["eleven", "twelve", "thirteen", "fourteen", "fifteen", "seventeen", "eighteen", "nineteen"],
    "seventeen": ["eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "eighteen", "nineteen"],
    "eighteen": ["eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "nineteen"],
    "nineteen": ["eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen"],

    // Numbers 20-100 (selected multiples of 10 for brevity)
    "twenty": ["thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety", "hundred"],
    "thirty": ["twenty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety", "hundred"],
    "forty": ["twenty", "thirty", "fifty", "sixty", "seventy", "eighty", "ninety", "hundred"],
    "fifty": ["twenty", "thirty", "forty", "sixty", "seventy", "eighty", "ninety", "hundred"],
    "sixty": ["twenty", "thirty", "forty", "fifty", "seventy", "eighty", "ninety", "hundred"],
    "seventy": ["twenty", "thirty", "forty", "fifty", "sixty", "eighty", "ninety", "hundred"],
    "eighty": ["twenty", "thirty", "forty", "fifty", "sixty", "seventy", "ninety", "hundred"],
    "ninety": ["twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "hundred"],
    "hundred": ["twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]
};